# require: rubocop-rspec # make specs compliant one day
# until then:

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  StyleGuideCopsOnly: true
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true

# See https://github.com/bbatsov/rubocop/issues/4637
Layout/SpaceAroundOperators:
  Enabled: false
